---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "B"
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
plugins:
  bandit:
    enabled: true
    config:
      python_version: 3
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.py"
exclude_paths:
- docs/
- tests/
- requirements/
- appveyor/aquarium/
- transistor/utility/browsercookie.py
